eLangdell @ OpenEd 2013
-----------------------

:Author: Sarah Glassmeyer
:Author1: Elmer Masters

Our eLangdell talk for OpenEd 2013, developed in public on GitHub

=== Topic Description: 

Christopher Columbus Langdell, professor at the Harvard Law School in the 19th Century,, developed the case law method of legal education, a method that continues to this day. In it, law students learn the law by reading court cases that interpret it. The eLangdell Press was conceived as a way to bring this method into the 21st century by creating open casebooks. After all, law is public domain material, and there are plenty of open source tools available to create the OER materials, so it should be relatively easy, right?

[red]*Wrong.*

This session will detail the experience of the Center for Computer-Assisted Legal Instruction staff?s quest to open up the Legal Textbook system. Topics covered will include the challenges faced with working with government and legal information, the unique issues of the legal academe, and the best practices we?ve developed in creating our casebooks. 

=== Outline of Talk:

25 minutes total

. Law School Pedagogy, CCLangdell and the caselaw method ( {Author} ) - 2-3 minutes
.. Pre-20th century apprecticeship/phiosophical study
.. Langdell, Harvard and reading cases late 19th century forward
. Original plan for eLangdell ({Author1}) - 3 minutes
. Content issues/problems - e.g. How to figure out what case is a "contracts" case, how to decide how much case is used, copyright of TOCs and getting open cases ({Author}) - 5 minutes
.. Brief mention of legal information ecosystem and why it sucks (e.g. No open index, just keynumber)
.. Cases cover several issues.  Plus have publisher copyrighted content
.. Compiled list of all contracts cases.  So we had this list of cases.  Then what? 
. Tech issues with putting open cases into a way for law profs to use ({Author1}) - 5 minutes
. Our Current set up.  ({Author}) - 3/4 minutes
.. breadcrumb approach. 4 types of pubishing formats for greatest chance of adoption - even print!  PDF most popular. Sad tromobone
.. Pay authors and CALI retains copyright.  We release CC
. The future possibilities ({Author1}) 5 minutes

If they have questions, meet us in the bar.
